from signal_ocean.scraped_fixtures import ScrapedFixture
from signal_ocean.util.pydantic_base import _to_pascal_case


def test_fixtures_field_names():
    api_fields = [
        "FixtureID",
        "MessageID",
        "ExternalMessageID",
        "ParsedPartID",
        "LineFrom",
        "LineTo",
        "InLineOrder",
        "Source",
        "UpdatedDate",
        "ReceivedDate",
        "IsDeleted",
        "LowConfidence",
        "ScrapedVesselName",
        "ScrapedDeadweight",
        "ScrapedYearBuilt",
        "IMO",
        "VesselName",
        "Deadweight",
        "YearBuilt",
        "LiquidCapacity",
        "VesselTypeID",
        "VesselType",
        "VesselClassID",
        "VesselClass",
        "CommercialOperatorID",
        "CommercialOperator",
        "ScrapedLaycan",
        "LaycanFrom",
        "LaycanTo",
        "ScrapedLoad",
        "LoadGeoID",
        "LoadName",
        "LoadTaxonomyID",
        "LoadTaxonomy",
        "ScrapedLoad2",
        "LoadGeoID2",
        "LoadName2",
        "LoadTaxonomyID2",
        "LoadTaxonomy2",
        "ScrapedDischarge",
        "ScrapedDischargeOptions",
        "DischargeGeoID",
        "DischargeName",
        "DischargeTaxonomyID",
        "DischargeTaxonomy",
        "ScrapedDischarge2",
        "DischargeGeoID2",
        "DischargeName2",
        "DischargeTaxonomyID2",
        "DischargeTaxonomy2",
        "ScrapedCharterer",
        "ChartererID",
        "Charterer",
        "ScrapedCargoType",
        "CargoTypeID",
        "CargoType",
        "CargoGroupID",
        "CargoGroup",
        "ScrapedQuantity",
        "Quantity",
        "QuantityBuffer",
        "QuantityFrom",
        "QuantityTo",
        "ScrapedRate",
        "ScrapedRateOptions",
        "RateValue",
        "RateType",
        "DemurrageRateValue",
        "DemurrageRateType",
        "OpenGeoID",
        "OpenGeoName",
        "OpenTaxonomyID",
        "OpenTaxonomy",
        "OpenDate",
        "ScrapedDeliveryDate",
        "DeliveryDateFrom",
        "DeliveryDateTo",
        "ScrapedDelivery",
        "DeliveryGeoID",
        "DeliveryName",
        "DeliveryTaxonomyID",
        "DeliveryTaxonomy",
        "ScrapedRedeliveryFrom",
        "RedeliveryFromGeoID",
        "RedeliveryFromName",
        "RedeliveryFromTaxonomyID",
        "RedeliveryFromTaxonomy",
        "ScrapedRedeliveryTo",
        "RedeliveryToGeoID",
        "RedeliveryToName",
        "RedeliveryToTaxonomyID",
        "RedeliveryToTaxonomy",
        "CharterTypeID",
        "CharterType",
        "FixtureStatusID",
        "FixtureStatus",
        "BrokerID",
        "Broker",
        "IsOwnersOption",
        "IsCOA",
        "Content",
        "Subject",
        "Sender",
        "IsPrivate",
        "IsInvalidated",
        "IsPartial",
        "Note",
    ]
    alias_to_field = {}
    for name, info in ScrapedFixture.model_fields.items():
        if info.validation_alias is not None:
            alias_to_field[str(info.validation_alias)] = name
        else:
            alias_to_field[_to_pascal_case(name)] = name

    for api_field in api_fields:
        assert api_field in alias_to_field, (
            f"API field {api_field!r} not in model"
        )

    assert sorted(alias_to_field[f] for f in api_fields) == sorted(
        ScrapedFixture.model_fields
    )
